services:
  - type: web
    name: jsp-distributors-api
    env: node
    plan: free
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
